### ISSUE TITLE
Is it neccesary to change the img_size of the model when upscaling?

### ISSUE THREAD

**Issue by WathomeBo** [ming053l/DRCT#32]
When the model is initialized, the img_size is set to 64. Is it neccesary to change the img_size of the model when upscaling images with other size?

**Comment by ming053l** [comment]
Hi

No, it is not necessary to change the img_size parameter when processing images of different sizes in this model. Here's why:

The img_size=64 parameter is mainly used for:
1. Initializing the position embeddings (if used, but in this model ape=False by default)
2. Setting up the patch embedding and unembedding layers

The model's architecture can handle different input sizes because:
1. The window-based self-attention mechanism operates on fixed window sizes (not dependent on input size)
2. The patch embed/unembed layers don't depend on the absolute image size since they work with relative patches

The model will automatically adjust to the input size during the forward pass. The img_size=64 parameter is more of an architectural hyperparameter that doesn't constrain the actual input size during inference.

If possible, it is recommended to set the image size to a multiple of window_size

Best Regards
